services:
  forumadb:
    container_name: forumadb
    image: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=0000
      - PGDATA=/data/postgres
    volumes:
      - forumadb:/data/forumadb
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-raufbisov@gmail.com}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "5050:80"
    networks:
      - postgres
    restart: unless-stopped

  eureka-server:
    image: raufbisov/eureka:latest
    container_name: eureka-server
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring

  apigw:
    image: raufbisov/apigw:latest
    container_name: apigw
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
    depends_on:
      - eureka-server

  auth:
    image: raufbisov/auth:latest
    container_name: auth
    ports:
      - "8081:8081"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - forumadb

  post:
    image: raufbisov/post:latest
    container_name: post
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - forumadb

  comment:
    image: raufbisov/comment:latest
    container_name: comment
    ports:
      - "8083:8083"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - forumadb

  interaction:
    image: raufbisov/interaction:latest
    container_name: interaction
    ports:
      - "8084:8084"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    networks:
      - spring
      - postgres
    depends_on:
      - eureka-server
      - forumadb
  # rabbitmq:
  #   image: rabbitmq:management-alpine
  #   container_name: rabbitmq
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"

networks:
  postgres:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16
  spring:
    driver: bridge

volumes:
  forumadb:
  pgadmin:
