server:
  port: 8084

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        - id: auth
          uri: lb://AUTH
          predicates:
            - Path=/api/auth/**
        - id: post
          uri: lb://POST
          predicates:
            - Path=/api/posts/**
        - id: comment
          uri: lb://COMMENT
          predicates:
            - Path=/api/comments/**
        - id: interaction
          uri: lb://INTERACTION
          predicates:
            - Path=/api/interactions/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
