spring:
  application:
    name: auth
  datasource:
    url: jdbc:postgresql://forumadb:5432/auth
    username: postgres
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
logging:
  level:
    root: WARN
eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

jwt:
  secret: "e30b806a93780d26fe0ecd5991b46a8df036b8faf22ffdf17f69b9b0299cd94d"

server:
  port: 8081
