server:
  port: 8084

spring:
  application:
    name: interaction
  datasource:
    url: jdbc:postgresql://localhost:5432/interaction
    username: postgres
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  # rabbitmq:
  #   addresses: localhost:5672

logging:
  level:
    root: WARN

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
# rabbitmq:
#   exchanges:
#     internal: internal.exchange
#   queue:
#     interaction: interaction.queue
#   routing-keys:
#     internal-interaction: internal.interaction.routing-key
