spring:
  application:
    name: comment
  datasource:
    url: jdbc:postgresql://forumadb:5432/comment
    username: postgres
    password: "0000"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka
    fetch-registry: true
    register-with-eureka: true

server:
  port: 8083
